export const GET_ALL_COMMENTS = 'GET_ALL_COMMENTS';
export const GET_ALL_COMMENTS_SUCCESS = 'GET_ALL_COMMENTS_SUCCESS';
export const GET_ALL_COMMENTS_FAILURE = 'GET_ALL_COMMENTS_FAILURE';

export const GET_PRODUCT = 'GET_PRODUCT';
export const GET_PRODUCT_SUCCESS = 'GET_PRODUCT_SUCCESS';
export const GET_PRODUCT_FAILURE = 'GET_PRODUCT_FAILURE';

export const ADD_COMMENT = 'ADD_COMMENT';
export const ADD_COMMENT_SUCCESS = 'ADD_COMMENT_SUCCESS';
export const ADD_COMMENT_FAILURE = 'ADD_COMMENT_FAILURE';

export const CLEAR_DEFAULT_COMMENTS = 'CLEAR_DEFAULT_COMMENTS';
export const CLEAR_DEFAULT_COMMENTS_SUCCESS = 'CLEAR_DEFAULT_COMMENTS_SUCCESS';
export const CLEAR_DEFAULT_COMMENTS_FAILURE = 'CLEAR_DEFAULT_COMMENTS_FAILURE';
